export const FEATURES_MAP: Record<string, { label: string; icon: string; type: "boolean" | "number" }> = {
  ac: { label: "Aire acondicionado", icon: "❄️", type: "boolean" },
  ambientes: { label: "Ambientes", icon: "🏡", type: "number" },
  balcon: { label: "Balcón", icon: "🌇", type: "boolean" },
  cable: { label: "TV por cable", icon: "📺", type: "boolean" },
  calefaccion: { label: "Calefacción", icon: "🔥", type: "boolean" },
  capacidad: { label: "Capacidad", icon: "👥", type: "number" },
  estacionamiento: { label: "Estacionamiento", icon: "🚗", type: "boolean" },
  fumadores: { label: "Apto fumadores", icon: "🚬", type: "boolean" },
  lavarropas: { label: "Lavarropas", icon: "🧺", type: "boolean" },
  mascotas: { label: "Apto mascotas", icon: "🐶", type: "boolean" },
  parrilla: { label: "Parrilla", icon: "🍖", type: "boolean" },
  patio: { label: "Patio", icon: "🌿", type: "boolean" },
  pileta: { label: "Pileta", icon: "🏊‍♂️", type: "boolean" },
  ropa_cama: { label: "Ropa de cama", icon: "🛏️", type: "boolean" },
  secador_pelo: { label: "Secador de pelo", icon: "💇‍♀️", type: "boolean" },
  seguridad: { label: "Seguridad", icon: "🔒", type: "boolean" },
  terraza: { label: "Terraza", icon: "🌞", type: "boolean" },
  tv: { label: "Televisor", icon: "📺", type: "boolean" },
  wifi: { label: "Wifi", icon: "📶", type: "boolean" },
};
